// AstroRemedyReport.jsx
import React from "react";
import { AlertCircle, CheckCircle2, MessageSquare } from "lucide-react";

export default function AstroRemedyReport() {
  return (
    <div className="min-h-screen bg-[#F7E3C7] text-gray-900 antialiased">
      {/* Top nav / small header */}
      <header className="max-w-6xl mx-auto px-4 pt-6 pb-2 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-full bg-white/60 border border-amber-200 flex items-center justify-center text-amber-700 font-bold">
            ✶
          </div>
          <nav className="hidden md:flex gap-6 text-sm text-gray-700">
            <a className="hover:underline">Home</a>
            <a className="hover:underline">Kundli Generation</a>
            <a className="hover:underline">AI Based Q&A</a>
            <a className="text-amber-700 font-semibold">Remedies</a>
          </nav>
        </div>
        <div className="text-sm text-gray-700 hidden md:block"> </div>
      </header>

      {/* small banner text */}
      <div className="max-w-6xl mx-auto px-4">
        <div className="text-amber-700 font-medium text-sm mb-4">
          We have remedies for everything
        </div>
      </div>

      {/* main card */}
      <main className="max-w-6xl mx-auto px-4 pb-12">
        <article className="bg-[#FFF3E6] border border-[#F2D6B2] rounded-2xl shadow-md p-8">
          {/* Kundli info pill */}
          <div className="mb-6">
            <div className="inline-flex items-center bg-[#F5D9A9] border border-[#EECF9A] rounded-lg px-4 py-2 text-sm text-gray-800 shadow-sm">
              <div className="mr-4">
                <div className="font-semibold">Kushal Shaw</div>
                <div className="text-xs text-gray-700">Age: 35</div>
              </div>

              <div className="ml-2 text-xs text-gray-700 flex flex-wrap gap-3">
                <span>• Date of birth: <strong className="ml-1">24-12-1986</strong></span>
                <span>• Time of birth: <strong className="ml-1">11:45am</strong></span>
                <span>• Sign: <strong className="ml-1">Capricorn</strong></span>
              </div>
            </div>
          </div>

          {/* Heading + meta */}
          <header className="mb-4">
            <h1 className="flex items-center gap-3 text-lg md:text-xl font-bold text-gray-900 mb-1">
              <AlertCircle className="w-5 h-5 text-amber-600" />
              Your Personalised Astro-Remedy Report
            </h1>

            <div className="text-sm text-gray-700">
              Generated by <strong>AI Astro Intelligence Engine™</strong> | Powered by Cosmic Alignment Model v2.9
            </div>
            <div className="text-sm text-gray-700 mt-2">✦ Observations from Your Kundli:</div>
          </header>

          <p className="text-sm text-gray-800 mb-4">
            Based on your planetary positions at the time of your birth, certain patterns have emerged that are
            currently influencing your mental, emotional, and career energies.
          </p>

          {/* Detected Issues */}
          <section className="mb-6">
            <h2 className="flex items-center gap-2 text-black font-semibold mb-3">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" className="inline-block">
                <circle cx="12" cy="12" r="10" stroke="#C43A2E" strokeWidth="1.2" />
                <path d="M12 8v5" stroke="#C43A2E" strokeWidth="1.4" strokeLinecap="round" />
                <circle cx="12" cy="16.3" r="0.6" fill="#C43A2E" />
              </svg>
              Detected Issues:
            </h2>

            <ol className="list-decimal ml-6 space-y-2 text-sm text-gray-800">
              <li>Emotional Overwhelm &amp; Overthinking</li>
              <li>Moon is slightly afflicted due to its alignment with Rahu, leading to mood instability and emotional sensitivity.</li>
              <li>Blocked Growth in Career &amp; Finance</li>
              <li>Saturn’s retrograde aspect in your 10th house is slowing down your momentum, especially in long-term goals.</li>
              <li>Lack of Stability in Relationships</li>
              <li>Venus in an unbalanced position is creating temporary misalignments in love and emotional bonds.</li>
            </ol>
          </section>

          {/* Remedies */}
          <section className="mb-6">
            <h2 className="flex items-center gap-2 text-black font-semibold mb-3">
              <CheckCircle2 className="w-5 h-5" />
              Remedies for Alignment &amp; Healing:
            </h2>

            <div className="space-y-6 text-sm text-gray-800">
              {/* 1 */}
              <div>
                <h3 className="font-semibold mb-2">1. 🧘 Mind &amp; Emotional Balance</h3>
                <ul className="list-disc ml-6 space-y-1">
                  <li>Every Monday before 9:00 AM, drink lukewarm water infused with tulsi leaves.</li>
                  <li>Meditate facing east for 7 minutes while silently chanting: <em>"Om Chandraya Namaha"</em>.</li>
                  <li>Sleep with a silver coin under your pillow for 11 consecutive nights.</li>
                </ul>
              </div>

              {/* 2 */}
              <div>
                <h3 className="font-semibold mb-2">2. 💼 Career &amp; Financial Unlocking</h3>
                <ul className="list-disc ml-6 space-y-1">
                  <li>On every Saturday evening, light a mustard oil diya under a Peepal tree (or indoors facing west).</li>
                  <li>Keep a piece of black tourmaline crystal near your workspace.</li>
                  <li>Avoid starting new financial tasks on Tuesdays and Saturdays for the next 21 days.</li>
                </ul>
              </div>

              {/* 3 */}
              <div>
                <h3 className="font-semibold mb-2">3. ❤️ Relationship Harmony</h3>
                <ul className="list-disc ml-6 space-y-1">
                  <li>Every Friday, wear something white or light pink and avoid arguments post-sunset.</li>
                  <li>Place rose petals soaked in milk in a small copper bowl in the southwest corner of your bedroom.</li>
                  <li>Whisper your desires to a rose quartz crystal and keep it under moonlight once a week.</li>
                </ul>
              </div>
            </div>
          </section>

          <p className="text-sm text-gray-800 mb-6">
            ✦ Follow these steps for the next 21 days consistently. Your energetic frequencies will begin to realign,
            reducing karmic blockages and attracting clarity and harmony.
          </p>

          <p className="text-sm font-medium mb-4">
            Would you like a version like this for love life, health, marriage timing, or spiritual growth?
          </p>

          {/* Ask Anything input */}
          <div className="mt-2">
            <div className="flex items-center gap-3 bg-white border border-[#E9D3B6] rounded-lg px-4 py-3">
              <MessageSquare className="w-5 h-5 text-amber-600" />
              <input
                type="text"
                placeholder="Ask Anything"
                className="flex-1 bg-transparent outline-none text-sm text-gray-800 placeholder-gray-500"
              />
              <button className="ml-3 bg-amber-600 text-white text-sm px-3 py-2 rounded-md">Send</button>
            </div>
          </div>
        </article>
      </main>
    </div>
  );
}
